### ISSUE TITLE
有时候查询会无法获得结果。

### ISSUE THREAD

**Issue by hot36952** [a26214311/poi-plugin-breed#1]
![qq 20190304013846](https://user-images.githubusercontent.com/21011227/53698985-7e467b00-3e1e-11e9-8f40-2dca9ea1fc57.jpg)
如图，经常会查询无法获得结果，有时候重启poi能解决，有时候不能。

**Comment by a26214311** [comment]
额，如果打开开发者面板没报错的话应该就是网速问题

**Comment by hot36952** [comment]
> 额，如果打开开发者面板没报错的话应该就是网速问题


![QQ截图20190311174625](https://user-images.githubusercontent.com/21011227/54114573-ad17af00-4425-11e9-9fb1-f107b82bf736.jpg)
我也不清楚这是不是报错，你说的网速问题是我的问题，我使用acgp代理，还是查询的服务器的问题？

**Comment by a26214311** [comment]
这个应该就是网络问题了

**Comment by hot36952** [comment]
所以问到底是谁的网络问题..？
